version: '3.8'

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    command: sleep infinity 
    container_name: AutoStruct
    volumes:
      - ..:/workspaces:cached